### ISSUE TITLE
Empty dataframe after merge

### ISSUE THREAD

**Issue by pickettj** [pickettj/jupyter_notebooks#2]
@iamlemec , can you tell me why I am ending up with an [empty dataframe? I am writing a script for a very simple merge](https://github.com/pickettj/jupyter_notebooks/blob/master/simple_dataframe_conversion.ipynb), but still ending up with trouble...

**Comment by iamlemec** [comment]
I'm guessing it's because there's no overlap in the `Loc_ID` values between `population` and `coords`. By default, `merge` will use an inner join, meaning it would come up empty in this case.

Maybe it could be that `Loc_ID` is secretly a different type in each dataframe. For instance it could be str in one and int in the other, or perhaps float. But that seems less likely.

**Comment by pickettj** [comment]
Thanks @iamlemec ! That actually helped me solve the problem. And it was every bit as boneheaded as you may have surmised...
